USE KTSDB;

CREATE TABLE IF NOT EXISTS user (
	user_id VARCHAR(20) NOT NULL UNIQUE,
	pw VARCHAR(50) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(20) NOT NULL,
	PRIMARY KEY (user_id)
) DEFAULT CHARSET=utf8;
